package demo.client.shared;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class Address implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("ID #")
   @javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "ADDRESS_ID_GENERATOR")
   @javax.persistence.Id
   @javax.persistence.SequenceGenerator(sequenceName = "ADDRESS_ID_SEQ", name = "ADDRESS_ID_GENERATOR")
   private java.lang.Long id;

   @org.kie.api.definition.type.Label(value = "Street Name")
   @org.hibernate.validator.constraints.NotEmpty
   private java.lang.String street;

   @org.kie.api.definition.type.Label(value = "Num #")
   private java.lang.Integer num;

   @org.kie.api.definition.type.Label(value = "CP")
   @org.hibernate.validator.constraints.NotEmpty
   private java.lang.String cp;

   @org.kie.api.definition.type.Label(value = "City")
   @org.hibernate.validator.constraints.NotEmpty
   private java.lang.String city;

   @org.kie.api.definition.type.Label(value = "Country")
   private java.lang.String country;

   public Address()
   {
   }

   public java.lang.Long getId()
   {
      return this.id;
   }

   public void setId(java.lang.Long id)
   {
      this.id = id;
   }

   public java.lang.String getStreet()
   {
      return this.street;
   }

   public void setStreet(java.lang.String street)
   {
      this.street = street;
   }

   public java.lang.Integer getNum()
   {
      return this.num;
   }

   public void setNum(java.lang.Integer num)
   {
      this.num = num;
   }

   public java.lang.String getCp()
   {
      return this.cp;
   }

   public void setCp(java.lang.String cp)
   {
      this.cp = cp;
   }

   public java.lang.String getCity()
   {
      return this.city;
   }

   public void setCity(java.lang.String city)
   {
      this.city = city;
   }

   public java.lang.String getCountry()
   {
      return this.country;
   }

   public void setCountry(java.lang.String country)
   {
      this.country = country;
   }

   public Address(java.lang.Long id, java.lang.String street,
         java.lang.Integer num, java.lang.String cp, java.lang.String city,
         java.lang.String country)
   {
      this.id = id;
      this.street = street;
      this.num = num;
      this.cp = cp;
      this.city = city;
      this.country = country;
   }

}
