package demo.client.shared;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class Department implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("ID #")
   @javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "DEPARTMENT_ID_GENERATOR")
   @javax.persistence.Id
   @javax.persistence.SequenceGenerator(sequenceName = "DEPARTMENT_ID_SEQ", name = "DEPARTMENT_ID_GENERATOR")
   private Long id;

   @org.kie.api.definition.type.Label("Dep. Name")
   @org.hibernate.validator.constraints.NotEmpty
   private String name;

   @org.kie.api.definition.type.Label("Dep. Description")
   @org.hibernate.validator.constraints.NotEmpty
   private String description;

   @org.kie.api.definition.type.Label("Address")
   @javax.persistence.ManyToOne(fetch = javax.persistence.FetchType.EAGER, cascade = { javax.persistence.CascadeType.ALL })
   private demo.client.shared.Address address;

   @javax.persistence.OneToMany(fetch = javax.persistence.FetchType.EAGER, cascade = { javax.persistence.CascadeType.ALL })
   @org.kie.api.definition.type.Label(value = "Employees")
   private java.util.List<User> employees;

   public Department()
   {
   }

   public Long getId()
   {
      return this.id;
   }

   public void setId(Long id)
   {
      this.id = id;
   }

   public String getName()
   {
      return this.name;
   }

   public void setName(String name)
   {
      this.name = name;
   }

   public String getDescription()
   {
      return this.description;
   }

   public void setDescription(String description)
   {
      this.description = description;
   }

   public demo.client.shared.Address getAddress()
   {
      return this.address;
   }

   public void setAddress(demo.client.shared.Address address)
   {
      this.address = address;
   }

   public java.util.List<User> getEmployees()
   {
      return this.employees;
   }

   public void setEmployees(java.util.List<User> employees)
   {
      this.employees = employees;
   }

   public Department(Long id, String name,
         String description, demo.client.shared.Address address,
         java.util.List<User> employees)
   {
      this.id = id;
      this.name = name;
      this.description = description;
      this.address = address;
      this.employees = employees;
   }

}
